# 算法正确率

In [1]:
import numpy as np

from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

# Train_Test_Split

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
shuffle_indexes = np.random.permutation(len(X))

In [8]:
shuffle_indexes

array([ 48,  72, 127,  28,  70,  73,  25,   6,  11, 102,  89, 140,  82,
        52,  36,  53,  69,  76,  90,  78, 122, 124,  39,  68,  77, 113,
       133, 138, 135,  92,  23,  99,  44, 104,   9,  27,  91,  43, 108,
        97, 137, 116,  37, 136,  55, 101, 112, 126, 107,  13,  16, 132,
        93, 100, 141,  87, 146,  20,  45,  24,  59,  58, 117,  81,  40,
        96,   8,  51,   0,  86,  15, 142, 109,  62,  83,  79,  10,  18,
        85,  34,  47, 144, 111,  33,  71,  22, 119,  60,  30,  64, 115,
        26, 131,  74,  38,  80, 118,  94,   1,  21,  84,  31, 110,  75,
        88, 123, 128, 103, 121,  32,  17,  63, 105, 139,  29, 143,  95,
        61, 106,  49,  67,   7,  56, 134,  42,   2,  35,  98,  14,  50,
       114, 147,   4,   5, 148, 129,  54,   3, 130,  65,  12,  46, 120,
        19, 145, 125, 149,  41,  66,  57])

In [9]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [10]:
test_size

30

In [11]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [12]:
test_indexes

array([ 48,  72, 127,  28,  70,  73,  25,   6,  11, 102,  89, 140,  82,
        52,  36,  53,  69,  76,  90,  78, 122, 124,  39,  68,  77, 113,
       133, 138, 135,  92])

In [13]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [23]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


# scikit-learn 中的 train_test_split

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [26]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


# accuracy_score

In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [28]:
knn_clf = KNeighborsClassifier(n_neighbors=6)

In [29]:
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=6, p=2,
           weights='uniform')

In [30]:
knn_clf.score(X_test, y_test)

0.9333333333333333