In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [6]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


# scikit-learn中的StandardScaler

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
standardScaler = StandardScaler()

In [9]:
standardScaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
standardScaler.mean_

array([5.86      , 3.05166667, 3.84833333, 1.23833333])

In [11]:
standardScaler.scale_

array([0.82121861, 0.41912276, 1.72959453, 0.76203492])

In [12]:
X_train = standardScaler.transform(X_train)

In [13]:
X_train

array([[ 0.0487081 , -0.12327335,  0.72367636,  0.73706158],
       [-0.56014318, -0.12327335,  0.37677424,  0.34337884],
       [ 0.0487081 ,  0.35391381,  0.5502253 ,  0.73706158],
       [-0.31660267, -0.12327335,  0.37677424,  0.34337884],
       [-0.43837292, -1.79342841,  0.08768915,  0.08092368],
       [ 0.77932964,  0.35391381,  0.72367636,  0.99951675],
       [ 0.29224861, -0.36186693,  0.49240828,  0.21215126],
       [-1.65607548, -1.79342841, -1.47337037, -1.23135214],
       [ 0.17047836, -2.03202199,  0.08768915, -0.31275907],
       [ 0.29224861, -0.60046051,  0.49240828, -0.05030391],
       [-1.0472242 , -0.12327335, -1.29991932, -1.36257972],
       [-0.92545395, -1.31624125, -0.49048105, -0.18153149],
       [ 0.77932964, -0.12327335,  1.12839549,  1.26197191],
       [ 1.02287015,  0.11532023,  1.01276145,  1.52442707],
       [ 1.63172143,  1.30828813,  1.30184655,  1.65565466],
       [ 0.41401887, -0.60046051,  0.5502253 ,  0.73706158],
       [ 0.77932964, -0.

In [14]:
X_test = standardScaler.transform(X_test)

In [15]:
X_test

array([[ 0.0487081 , -0.12327335,  0.20332318,  0.34337884],
       [-1.0472242 ,  0.59250739, -1.41555336, -1.36257972],
       [ 1.02287015,  0.11532023,  0.49240828,  0.34337884],
       [-0.43837292,  1.06969455, -1.47337037, -1.36257972],
       [-1.0472242 ,  0.35391381, -1.53118739, -1.36257972],
       [-0.56014318,  2.02406887, -1.47337037, -1.10012456],
       [-0.19483241,  3.21703677, -1.35773634, -1.10012456],
       [ 0.65755938,  0.11532023,  0.95494443,  0.73706158],
       [-1.0472242 ,  0.83110097, -1.29991932, -1.10012456],
       [-1.16899446,  1.30828813, -1.41555336, -1.49380731],
       [-1.16899446,  0.11532023, -1.35773634, -1.36257972],
       [-1.16899446, -0.12327335, -1.41555336, -1.36257972],
       [-0.07306215, -0.83905409,  0.02987213, -0.05030391],
       [ 2.11880246, -0.12327335,  1.59093165,  1.13074433],
       [ 0.17047836, -2.03202199,  0.66585934,  0.34337884],
       [-0.92545395,  1.78547529, -1.35773634, -1.23135214],
       [ 0.65755938,  0.

In [16]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
knn_clf = KNeighborsClassifier(n_neighbors=3)

In [18]:
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [19]:
knn_clf.score(X_test, y_test)

0.9